# Generated by Django 3.2.8 on 2021-10-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, default='Guest User', max_length=50)),
                ('email', models.EmailField(default='user@example.com', max_length=100)),
                ('password', models.CharField(blank=True, default='', max_length=500)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('disabled', models.BooleanField(blank=True, default=False)),
                ('user_image', models.URLField(blank=True, default='')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('coins', models.BigIntegerField(default=0)),
                ('gender', models.CharField(choices=[('Unknown', 'Not Specific'), ('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default='Unknown', max_length=20)),
                ('provider', models.CharField(blank=True, default='Password', max_length=50)),
                ('create_location', models.CharField(default='India', max_length=300)),
                ('current_location', models.CharField(default='India', max_length=300)),
                ('last_sign_in', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Firebase Users',
                'verbose_name_plural': 'Firebase Users',
                'db_table': 'firebase_users',
            },
        ),
    ]
